Add test framework
chipsalliance/rocket-chip pull request #2991
Opened 2022-05-19 16:31 UTC by geekLucian

**Related issue**: 

**Type of change**: feature request

**Impact**: API addition (no impact on existing code)

**Development Phase**: proposal

**Release Notes**

Add test framework from @sequencer's [playground](https://github.com/sequencer/playground/tree/master/sanitytests/rocketchip). Still work in progress.

2022-05-19 16:35 UTC, sequencer commented on build.sc
> +  }
Since the test used the fesvr, you may need introduce spike as well.

2022-05-19 16:49 UTC, michael-etzkorn commented
Relevant issue:
https://github.com/chipsalliance/rocket-chip/issues/2953 

I've yet to look over the details of this but I'd like to see more `test/scala` at some point for development. 

My two cents on structuring the RTL based testing directory-wise is that it should be mergable https://github.com/chipsalliance/rocket-chip/tree/master/src/main/scala/unittest and ideally be invokable within `regression`

2022-05-19 18:12 UTC, sequencer commented
> I don't think I understand why this is in a separate sanitytests directory instead of src/test. The changes also introduce more places where chisel/firrtl version numbers are encoded, which increases maintenance burden slightly.

I agree, I thought @geekLucian just copy-paste from my own repository, which obviously needs more refactor to make it fit into rocket-chip.

> This approach also seems to reimplement some functionality already in chiseltest. What functionality does this approach support over chiseltest?

IIRC, this approach is copy-paste from the rocket-chip original test suite, and has no relation to the chiseltest.
programs are supported to be loaded via DM, since the DMI, or JTAG-VPI depends on DPI, which makes chiseltest impossible to test it.

> Lastly, if we do move forwards with this approach, I think the csrc files should symlink the existing files, and the bootrom should use the default one in RC (Don't we want to test that that bootrom works?).

Agree, `bootrom` should use the original `bootrom` from Rocket-Chip.

2022-05-19 18:14 UTC, sequencer commented on build.sc
> +object sanitytests extends ScalaModule with TestModule.Utest {
This should live under `rocketchip` project

2022-05-19 18:28 UTC, sequencer requested changes

2022-05-19 18:28 UTC, sequencer commented on build.sc
> +  }
this should inherit from `rocketchip` object

2022-05-19 18:28 UTC, sequencer commented on build.sc
> +  )
same here.

2022-05-19 18:28 UTC, sequencer commented on build.sc
> +    T.ctx.dest
You should introduce dependency of `spike` aka riscv-isa-sim. for `csrc` you need use the original `csrc`.

2022-05-19 18:28 UTC, sequencer commented on sanitytests/src/TestConfig.scala
> +          ).call()
I think compiling of `bootrom` should live outside `TestFramework`, it should somehow live in mill, which makes it being able to be cached by the build system.

2022-05-19 18:28 UTC, sequencer commented on sanitytests/src/VerilatorTest.scala
> +    }
The build of test cases should also live inside the build system.
and it depends a C compiler, which should be optional as well, IMO, the RISCV toolchain is stable enough, which is possible to use the toolchain from upstream(LLVM or GCC).
You can install it in the GItHub Action like playground did.

2022-05-19 18:35 UTC, sequencer commented
> I don't think I understand why this is in a separate sanitytests directory instead of `src/test`.

The `src/test` uses `ScalaTest` by default, while I use the `uTest`, I think it is reasonable to stick on `ScalaTest`, since I didn't depends on the special features of `uTest`.

As for the packaging issue. IMHO, a more fine granularity provides flexibility, the architect part can be split out from the `src/test` living in another package, like what chisel did [here](https://github.com/chipsalliance/chisel3/tree/master/integration-tests/src/test/scala).

2022-07-01 03:57 UTC, sequencer requested changes
You are going to the right direction!

2022-07-01 03:57 UTC, sequencer commented on build.sc
> +    rocketchip.`pomSettings`()
why

2022-07-01 03:57 UTC, sequencer commented on build.sc
> +    }
make this as an external function, so that others can add programs as test payloads.

2022-07-01 03:57 UTC, sequencer commented on build.sc
> +        s"${resource("resources/csrc/hello.c")}",
I personal prefer using a `testcase/hello` directory to store these tests.

2022-07-01 03:57 UTC, sequencer commented on common.sc
> +  "chisel3-plugin" -> "3.5.3"
You need to create another PR to bump this.

2022-08-17 14:51 UTC, closed without merging