feat: convert unittest to chisel3
chipsalliance/rocket-chip pull request #3045
Opened 2022-09-14 00:10 UTC by tianrui-wei

Convert unittest subdir to use chisel3

Signed-off-by: Tianrui Wei <tianrui@tianruiwei.com>

**Type of change**: other enhancement

**Impact**: no functional change

**Development Phase**: implementation

**Release Notes**

2022-09-14 05:41 UTC, sequencer requested changes

2022-09-14 05:41 UTC, sequencer commented on src/main/scala/unittest/UnitTest.scala
>    val io = new Bundle {
add IO wrapper

2022-09-14 22:03 UTC, tianrui-wei commented
Addressed, thanks for reviewing

2022-09-15 23:15 UTC, tianrui-wei commented on src/main/scala/unittest/UnitTest.scala
>    val io = new Bundle {
Addressed in the new commit

2022-09-16 05:49 UTC, jerryz123 approved these changes

2022-09-18 05:29 UTC, sequencer approved these changes

2022-09-18 05:29 UTC, merged