refactor TLB to chisel3.
chipsalliance/rocket-chip pull request #3056
Opened 2022-09-14 20:32 UTC by SingularityKChen

**Related issue**: 

**Type of change**: other enhancement

**Impact**: no functional change

**Development Phase**: implementation

**Release Notes**

Refactor TLB.scala to chisel3 style.

2022-09-18 05:56 UTC, sequencer commented
TLB doc is merged, plz rebase to master.

2022-09-19 03:51 UTC, SingularityKChen commented
> TLB doc is merged, plz rebase to master.

Rebased.

2022-10-02 16:38 UTC, sequencer commented on src/main/scala/rocket/TLB.scala
> +    val kill = Input(Bool()) // suppress a TLB refill, one cycle after a miss
why refactor the documentation code style?

2022-10-02 17:12 UTC, sequencer requested changes
Don't change anything other than chisel3 refactor.

2022-10-03 03:37 UTC, sequencer requested changes

2022-10-03 03:37 UTC, sequencer commented on src/main/scala/rocket/TLB.scala
> +  val state = RegInit(init=s_ready)
```suggestion
  val state = RegInit(s_ready)
```

2022-10-03 07:16 UTC, sequencer requested changes

2022-10-03 07:16 UTC, sequencer commented on src/main/scala/rocket/TLB.scala
> +  val cmd  = Bits(M_SZ.W)
```suggestion
  val cmd  = UInt(M_SZ.W)
```

2022-10-03 07:16 UTC, sequencer commented on src/main/scala/rocket/TLB.scala
> +  val deny_access_to_debug = mpu_priv <= PRV.M .U&& p(DebugModuleKey).map(dmp => dmp.address.contains(mpu_physaddr)).getOrElse(false.B)
```suggestion
  val deny_access_to_debug = mpu_priv <= PRV.M.U && p(DebugModuleKey).map(dmp => dmp.address.contains(mpu_physaddr)).getOrElse(false.B)
```

2022-10-03 10:34 UTC, sequencer requested changes

2022-10-03 10:34 UTC, sequencer commented on src/main/scala/rocket/TLB.scala
> +  val cmd  =UInt(M_SZ.W)
```suggestion
  val cmd  = UInt(M_SZ.W)
```

2022-10-04 05:03 UTC, closed without merging