refactor ICache to chisel3.
chipsalliance/rocket-chip pull request #3064
Opened 2022-09-16 14:24 UTC by SingularityKChen

**Related issue**: 

**Type of change**: other enhancement

**Impact**: no functional change

**Development Phase**: implementation

**Release Notes**

Refactor ICache.scala to chisel3 style.

2022-09-17 00:00 UTC, SingularityKChen commented on src/main/scala/rocket/ICache.scala
> +      s1_dout := VecInit(Seq.fill(nWays){0.U(dECC.width(wordBits).W)})
Not sure whether these two lines introduce the function bug.

2022-09-20 05:24 UTC, sequencer requested changes

2022-09-20 05:24 UTC, sequencer commented on src/main/scala/rocket/ICache.scala
> +  val s1_valid = RegInit(init=false.B)
```suggestion
  val s1_valid = RegInit(false.B)
```

2022-09-20 05:24 UTC, sequencer commented on src/main/scala/rocket/ICache.scala
> +  val vb_array = RegInit(init=0.U(nSets*nWays))
```suggestion
  val vb_array = RegInit(init=0.U((nSets*nWays).W))
```

2022-09-20 05:24 UTC, sequencer commented on src/main/scala/rocket/ICache.scala
> +  val invalidate = WireDefault(init = io.invalidate)
```suggestion
  val invalidate = WireDefault(io.invalidate)
```

2022-09-20 05:24 UTC, sequencer commented on src/main/scala/rocket/ICache.scala
> +  val s2_scratchpad_word_addr = Cat(s2_hit_way, Mux(s2_slaveValid, s1s3_slaveAddr, io.s2_vaddr)(untagBits-1, log2Ceil(wordBits/8)), 0.U(log2Ceil(wordBits/8)))
```suggestion
  val s2_scratchpad_word_addr = Cat(s2_hit_way, Mux(s2_slaveValid, s1s3_slaveAddr, io.s2_vaddr)(untagBits-1, log2Ceil(wordBits/8)), 0.U(log2Ceil(wordBits/8).W))
```

2022-10-02 16:43 UTC, sequencer approved these changes

2022-10-02 16:43 UTC, merged