Add TLFixedDelayer
chipsalliance/rocket-chip pull request #3512
Opened 2023-10-18 13:08 UTC by cyyself

**Type of change**: feature request

**Impact**: no functional change

**Development Phase**: implementation

**Release Notes**

Add TLFixedDelayer for memory performance exploration in different memory latency.

2023-10-22 00:47 UTC, jerryhethatday commented
Is this only for simulation？

2023-10-22 00:52 UTC, jerryz123 requested changes

2023-10-22 00:52 UTC, jerryz123 commented on src/main/scala/tilelink/Delayer.scala
> +  val node = TLAdapterNode()
This should be an `IdentityNode`

2023-11-13 10:29 UTC, cyyself commented
As a more general #3520 for all DecoupledIO being merged, this PR will not be needed anymore.

2023-11-13 10:29 UTC, closed without merging